name = "GPUCellListSPH"
uuid = "0fae8f6c-cbdc-43f7-8a26-631b812a57c9"
authors = ["Vladimir Arnautov"]
version = "1.0.0-DEV"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[compat]
julia = "1"
CUDA = "4", "5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
